In [3]:
import os
import shutil
import tensorflow as tf
import numpy as np
import matplotlib.image as mpimg
from tensorflow.keras.optimizers import RMSprop
from tensorflow.keras.preprocessing.image import ImageDataGenerator

List = os.listdir('..\\mrlEyes_2018_01')

for i in List[1:len(List)-1]:
    data_list = os.listdir('..\\mrlEyes_2018_01'+'\\'+i)
    for j in data_list:
        if j[16]=='0':
            shutil.copyfile('../mrlEyes_2018_01'+'/'+i+'/'+j,'D:/AIML/Project/Data/eyes_closed/'+j)
        else:
            shutil.copyfile('../mrlEyes_2018_01'+'/'+i+'/'+j,'D:/AIML/Project/Data/eyes_open/'+j)

In [1]:
def split_data(SOURCE, TRAINING, TESTING, SPLIT_SIZE):
    ls = os.listdir(SOURCE)
    l = len(os.listdir(SOURCE))
    for i,j in enumerate(ls):
        if os.path.getsize(SOURCE+j)==0:
            print(j+"is zero length, so ignoring")
            continue
        if i<l*SPLIT_SIZE:
            shutil.copyfile(SOURCE+j,TRAINING+j)
        else:
            shutil.copyfile(SOURCE+j,TESTING+j)

In [4]:
SOURCE = 'D:/AIML/train/Closed/'
TRAINING = 'D:/AIML/Project/SleepData/Training/closed/'
TESTING = 'D:/AIML/Project/SleepData/Testing/closed/'
split_data(SOURCE, TRAINING, TESTING,0.8)
SOURCE = 'D:/AIML/train/Open/'
TRAINING = 'D:/AIML/Project/SleepData/Training/open/'
TESTING = 'D:/AIML/Project/SleepData/Testing/open/'
split_data(SOURCE, TRAINING, TESTING,0.8)

In [11]:
error_list = []
List = os.listdir('D:/AIML/Project/Data/Training/open/')
for i in List:
    j = mpimg.imread('D:/AIML/Project/Data/Training/open/'+i)
    j = np.asarray(j)
    if len(j.shape)==3:
        error_list.append(i)

In [11]:
from numpy import *
import math as m

In [2]:
a = zeros((3,3))

In [3]:
b = ones((a.shape[0],1))

In [4]:
c = hstack((b,a))

In [8]:
d = array([c[:,0]]).T

In [52]:
alpha = 10*math.pi/180
e = 5*math.pi/180
r = 4

In [53]:
x = 4*m.cos(alpha)*m.cos(e)
y = 4*m.sin(alpha)*m.cos(e)
z = 4*m.sin(e)

In [54]:
(x,y,z)

(3.9242410487616275, 0.6919495757003578, 0.34862297099063266)

In [57]:
pi/180

0.017453292519943295

In [10]:
(3.92, 0.69, 0.34)


(3.92, 0.69, 0.34)

In [12]:
def sph_to_cart(epsilon,alpha, r):
    p = zeros(3)  # Position vector 
    t = pi/180
  # Your code here
    alpha = t*alpha
    epsilon = t*epsilon
    x = r*cos(alpha)*cos(epsilon)
    y = r*sin(alpha)*cos(epsilon)
    z = r*sin(epsilon)
    p = array([[x,y,z]])
    return p

In [13]:
epsilon = 5
alpha = 10
r = 4
p = sph_to_cart(epsilon,alpha, r)
print(p)

[[3.92424105 0.69194958 0.34862297]]


In [14]:
def estimate_params(P):
    """
    Estimate parameters from sensor readings in the Cartesian frame.
    Each row in the P matrix contains a single 3D point measurement;
    the matrix P has size n x 3 (for n points). The format is:
  
    P = [[x1, y1, z1],
       [x2, x2, z2], ...]
       
    where all coordinate values are in metres. Three parameters are
    required to fit the plane, a, b, and c, according to the equation
  
    z = a + bx + cy
  
    The function should retrn the parameters as a NumPy array of size
    three, in the order [a, b, c].
    """
    param_est = zeros(3)
  
    # Your code here
    A = hstack((ones((P.shape[0],1)),P[:,:2]))
    B = array([P[:,2]]).T
  
    param_est = dot(linalg.inv(A),B)
    return param_est.T

In [19]:
meas = np.array([[pi/3, 0, 5],
                 [pi/4, pi/4, 7],
                 [pi/6, pi/2, 4],
                 [pi/5, 3*pi/4, 6],
                 [pi/8, pi, 3]])

print(meas)

A = hstack((ones((meas.shape[0],1)),meas[:,:2]))
print(A)
B = array([meas[:,2]]).T
print(B)

[[1.04719755 0.         5.        ]
 [0.78539816 0.78539816 7.        ]
 [0.52359878 1.57079633 4.        ]
 [0.62831853 2.35619449 6.        ]
 [0.39269908 3.14159265 3.        ]]
[[1.         1.04719755 0.        ]
 [1.         0.78539816 0.78539816]
 [1.         0.52359878 1.57079633]
 [1.         0.62831853 2.35619449]
 [1.         0.39269908 3.14159265]]
[[5.]
 [7.]
 [4.]
 [6.]
 [3.]]


In [23]:
solv = linalg.lstsq(A, B)

<ipython-input-23-18e95f0cc43c>:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  solv = linalg.lstsq(A, B)


In [27]:
solv[0].T.squeeze()

array([2.25      , 3.87133645, 0.0860297 ])